[package]
name = "expmnt"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
bitdemo = { path = "./bitdemo" }
cons = { path = "./cons-rs" }
proc-macro-playground = { path = "./proc-macro-playground" }
rustcomp = { path = "./rustcomp" }
